"""change Event table fields to include original_event_url and category

Revision ID: 080183cd57a6
Revises: c8a1aeffb4fb
Create Date: 2025-10-21 10:17:10.940547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080183cd57a6'
down_revision = 'c8a1aeffb4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_event_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('original_event_category', sa.String(), nullable=True))
        batch_op.drop_column('event_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('original_event_category')
        batch_op.drop_column('original_event_url')

    # ### end Alembic commands ###
