"""make event.original_event_id nullable

Revision ID: 089d3acb317f
Revises: 90baa8635351
Create Date: 2025-10-30 14:49:55.431396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089d3acb317f'
down_revision = '90baa8635351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('original_event_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('original_event_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
