"""add Event.hash

Revision ID: 102bda3f29a8
Revises: 403bca607891
Create Date: 2025-12-14 11:11:09.890106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102bda3f29a8'
down_revision = '403bca607891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('hash')

    # ### end Alembic commands ###
