"""add Event.feed_id

Revision ID: 19e3999eeaec
Revises: 8b203a709c95
Create Date: 2025-12-13 21:28:20.497392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e3999eeaec'
down_revision = '8b203a709c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_event_feed_id'), ['feed_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_event_feed_id_feed'), 'feed', ['feed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_feed_id_feed'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_feed_id'))
        batch_op.drop_column('feed_id')

    # ### end Alembic commands ###
