"""collection table and collection-event association table

Revision ID: 29921b992e59
Revises: 910d9f5eb8ec
Create Date: 2025-10-03 14:30:05.886526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29921b992e59'
down_revision = '910d9f5eb8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_user_id'), ['user_id'], unique=False)

    op.create_table('collections',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'event_id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_time')
        batch_op.drop_column('start_date')
        batch_op.drop_column('description')

    op.drop_table('collections')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_user_id'))
        batch_op.drop_index(batch_op.f('ix_collection_timestamp'))

    op.drop_table('collection')
    # ### end Alembic commands ###
