"""Organization.name is indexed and unique

Revision ID: 403bca607891
Revises: 857943062f0b
Create Date: 2025-12-14 09:38:48.860318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403bca607891'
down_revision = '857943062f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_name'))

    # ### end Alembic commands ###
