"""add organization table

Revision ID: 414816941562
Revises: bb8220f0ef81
Create Date: 2025-11-30 17:27:24.486914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414816941562'
down_revision = 'bb8220f0ef81'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_event_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_event_organization_id', 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_organization_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_timestamp'))

    op.drop_table('organization')
    # ### end Alembic commands ###