"""add location fields to Event table

Revision ID: 728086035bc1
Revises: dda3cf4e9896
Create Date: 2025-10-19 18:24:19.353691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728086035bc1'
down_revision = 'dda3cf4e9896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_desc', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location_geojson', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location_geojson')
        batch_op.drop_column('location_desc')

    # ### end Alembic commands ###
