"""Event ends_at is nullable

Revision ID: 80d48a432013
Revises: a645ce4347da
Create Date: 2025-11-09 08:52:39.124771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d48a432013'
down_revision = 'a645ce4347da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('ends_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('ends_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
