"""remodel as org-event and org-feed

Revision ID: 857943062f0b
Revises: 19e3999eeaec
Create Date: 2025-12-13 21:49:02.405896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857943062f0b'
down_revision = '19e3999eeaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.alter_column('feed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_event_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_event_organization_id_organization'), 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_organization_id_organization'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_organization_id'))
        batch_op.alter_column('feed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
