"""remodel as Org-Feed-Event

Revision ID: 8b203a709c95
Revises: 414816941562
Create Date: 2025-12-13 21:24:58.606306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b203a709c95'
down_revision = '414816941562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_organization_id'))
        batch_op.drop_index(batch_op.f('ix_event_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_event_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_event_organization_id'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_event_organization_id'), 'organization', ['organization_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_event_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_event_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###
