"""add Event original id

Revision ID: 90baa8635351
Revises: 1e5d1458618e
Create Date: 2025-10-30 14:46:45.109509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90baa8635351'
down_revision = '1e5d1458618e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_event_id', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_event_original_event_id'), ['original_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_original_event_id'))
        batch_op.drop_column('original_event_id')

    # ### end Alembic commands ###
