"""add followers junction table

Revision ID: 910d9f5eb8ec
Revises: 53e40d1cfd03
Create Date: 2025-09-18 19:31:47.038441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910d9f5eb8ec'
down_revision = '53e40d1cfd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
