"""Refactor Event start and end times

Revision ID: a645ce4347da
Revises: 089d3acb317f
Create Date: 2025-10-30 15:29:51.316964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a645ce4347da'
down_revision = '089d3acb317f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ends_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('start_time')
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))
        batch_op.drop_column('ends_at')
        batch_op.drop_column('starts_at')

    # ### end Alembic commands ###
