"""Event lat and lon coords

Revision ID: bb8220f0ef81
Revises: 80d48a432013
Create Date: 2025-11-09 12:20:03.193242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8220f0ef81'
down_revision = '80d48a432013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location_lon')
        batch_op.drop_column('location_lat')

    # ### end Alembic commands ###
