"""rebase

Revision ID: d785b4d0971c
Revises: 
Create Date: 2025-12-14 14:50:25.468503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd785b4d0971c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_collection_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection'))
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_user_id'), ['user_id'], unique=False)

    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('last_refresh', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_feed_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed'))
    )
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_last_refresh'), ['last_refresh'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_user_id'), ['user_id'], unique=False)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name=op.f('fk_followers_followed_id_user')),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_followers_follower_id_user')),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('pk_followers'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('location_desc', sa.String(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('location_geojson', sa.String(), nullable=True),
    sa.Column('original_event_id', sa.String(length=50), nullable=True),
    sa.Column('original_event_url', sa.String(), nullable=True),
    sa.Column('original_event_category', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name=op.f('fk_event_feed_id_feed')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_event_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_original_event_id'), ['original_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_user_id'), ['user_id'], unique=False)

    op.create_table('collections',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_collections_collection_id_collection')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_collections_event_id_event')),
    sa.PrimaryKeyConstraint('collection_id', 'event_id', name=op.f('pk_collections'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_event_original_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_feed_id'))

    op.drop_table('event')
    op.drop_table('followers')
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_user_id'))
        batch_op.drop_index(batch_op.f('ix_feed_timestamp'))
        batch_op.drop_index(batch_op.f('ix_feed_last_refresh'))

    op.drop_table('feed')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_user_id'))
        batch_op.drop_index(batch_op.f('ix_collection_timestamp'))

    op.drop_table('collection')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_account_type'))

    op.drop_table('user')
    # ### end Alembic commands ###
